# Generated by Django 5.0.6 on 2024-06-08 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ToDoApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"is_superuser": False},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="fecha_final",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="fecha_inicio",
            field=models.DateTimeField(),
        ),
    ]
